name: Deploy QuizSpark

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy Infrastructure
        run: |
          cd terraform
          terraform init
          terraform plan -out=tfplan \
            -var="supabase_url=${{ secrets.SUPABASE_URL }}" \
            -var="supabase_key=${{ secrets.SUPABASE_KEY }}" \
            -var="jwt_secret=${{ secrets.JWT_SECRET }}"
          terraform apply -auto-approve \
            -var="supabase_url=${{ secrets.SUPABASE_URL }}" \
            -var="supabase_key=${{ secrets.SUPABASE_KEY }}" \
            -var="jwt_secret=${{ secrets.JWT_SECRET }}"

      - name: Deploy Frontend
        run: |
          cd frontend
          npm install
          npm run build
          aws s3 sync dist/ s3://quizspark-frontend --delete 